### ISSUE TITLE
The tx broadcast notification stays when 2 transactions are sent in succession

### ISSUE THREAD

**Issue by packetflow** [pirl/PirlApp2.0#16]
**Version** PirlApp2.0 Beta 1
**System** Windows 10 x64

When we send 2 transactions directly one after another, the *Sending your transaction to the blockchain* notification stays. The first transaction notification was not closed. The tx is not sent out and the app needs to be restarted to recover from the problem.

![2020-05-29_22h31_53](https://user-images.githubusercontent.com/22841250/83303208-f146c900-a1fc-11ea-8e34-c7a1626181b9.png)

**Comment by masterdubs** [comment]
Fixed in new version
